//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace 11111
{
    using System;
    using ICSSoft.STORMNET;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// .
    /// </summary>
    // *** Start programmer edit section *** (NewClass1 CustomAttributes)

    // *** End programmer edit section *** (NewClass1 CustomAttributes)
    [AutoAltered()]
    [Caption("")]
    public class NewClass1 : ICSSoft.STORMNET.DataObject
    {

        // *** Start programmer edit section *** (NewClass1 CustomMembers)

        // *** End programmer edit section *** (NewClass1 CustomMembers)


        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
        }

    }
}
