//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace 11111.WebAPI.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using ICSSoft.STORMNET;
    using Microsoft.AspNetCore.Mvc;
    using 11111;
    using 11111.ApplicationLayer.DTO;
    using 11111.ApplicationLayer.DTO.NewClass1;
    using 11111.ApplicationLayer.Helpers;
    using 11111.ApplicationLayer.Services;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Контроллер для NewClass1.
    /// </summary>
    [ApiController]
    [Route("[controller]")]
    public partial class NewClass1Controller : ControllerBase
    {
        private readonly INewClass1Service _newClass1Service;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="NewClass1Controller"/>.
        /// </summary>
        /// <param name="newClass1Service">Сервис для работы с NewClass1.</param>
        public NewClass1Controller(INewClass1Service newClass1Service)
        {
            _newClass1Service = newClass1Service;
        }

        // *** Start programmer edit section *** (Custom constructors)

        // *** End programmer edit section *** (Custom constructors)

        /// <summary>
        /// Удалить NewClass1.
        /// </summary>
        /// <param name="id">GUID удаляемого объекта.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpDelete("{id:guid}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                await _newClass1Service.Delete(id);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении NewClass1", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Удалить все NewClass1 для переданных id.
        /// </summary>
        /// <param name="ids">GUIDы удаляемых объектов.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpPost("DeleteAll")]
        public async Task<IActionResult> DeleteAll([FromBody] List<Guid> ids)
        {
            if (ids == null || !ids.Any())
            {
                return BadRequest();
            }

            try
            {
                await _newClass1Service.DeleteAll(ids);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении NewClass1", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom public methods)

        // *** End programmer edit section *** (Custom public methods)

        /// <summary>
        /// Получить список всех NewClass1.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Список NewClass1.</returns>
        private async Task<ActionResult<GetAllRequestResult<TDto>>> GetAll<TDto>(int? perPage = null, int? page = null, string[] sorting = null, FilterDtoBase filter = null)
            where TDto : NewClass1DtoBase, new()
        {
            try
            {
                Task<IEnumerable<TDto>> getAllTask = _newClass1Service.GetAll<TDto>(perPage, page, sorting, filter);
                Task<int> countTask = _newClass1Service.Count<TDto>(filter);

                IEnumerable<TDto> data = await getAllTask;
                int count = await countTask;
                GetAllRequestResult<TDto> result = new GetAllRequestResult<TDto>() { Records = data, Count = count };

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении NewClass1", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить NewClass1 по идентификатору.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns>NewClass1 в форме указанного DTO, если найден.</returns>
        private async Task<ActionResult<TDto>> GetById<TDto>(Guid id)
            where TDto : NewClass1DtoBase, new()
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                TDto result = await _newClass1Service.GetById<TDto>(id);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении NewClass1 по id", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить общее количество NewClass1.
        /// </summary>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Количество NewClass1.</returns>
        private async Task<ActionResult<int>> GetCount<TDto>(FilterDtoBase filter = null)
            where TDto : NewClass1DtoBase, new()
        {
            try
            {
                int result = await _newClass1Service.Count<TDto>(filter);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении кол-ва NewClass1", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom private methods)

        // *** End programmer edit section *** (Custom private methods)
    }
}
