//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { DataTableFilterMeta, DataTableSortMeta } from 'primereact/datatable';

import axiosInstance from '@/api/instance';
import { IBaseNewClass1 } from '@/types/NewClass1.types';
import { getQueryString } from '@/utils/queryStringConverter';
import { SearchColumnsParam } from '@/types/helpers/SearchColumnsParam';

// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export const NewClass1Service = {
  async GetAllNewClass1(
    viewName: string,
    perPage?: number,
    page?: number,
    sorting?: DataTableSortMeta[],
    filter?: DataTableFilterMeta,
    search?: SearchColumnsParam
  ) {
    const queryStr = getQueryString(perPage, page, sorting, filter, search);
    return await axiosInstance.get(`/newclass1/${viewName}${queryStr}`);
  },

  async GetNewClass1(id: string, viewName: string) {
    return await axiosInstance.get(`/newclass1/${viewName}/${id}`);
  },

  async CreateNewClass1<T extends IBaseNewClass1>(data: T, viewName: string) {
    const response = await axiosInstance.post(`/newclass1/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async UpdateNewClass1<T extends IBaseNewClass1>(data: T, viewName: string) {
    const response = await axiosInstance.put(`/newclass1/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async DeleteNewClass1(id: string) {
    return await axiosInstance.delete(`/newclass1/${id}`);
  },

  async DeleteAllNewClass1(ids: string[]) {
    return await axiosInstance.post(`/newclass1/DeleteAll`, ids, {
      headers: {
        'Content-Type': 'application/json',
      },
    });
  },

  async GetCount(viewName: string) {
    return await axiosInstance.get(`/newclass1/${viewName}/count`);
  },

  // *** Start programmer edit section *** (Custom methods)

  // *** End programmer edit section *** (Custom methods)
};
