//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
export enum tView {
  // *** Start programmer edit section *** (Additional views)
  // *** End programmer edit section *** (Additional views)
}
