//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { NewClass1Service } from '@/services/NewClass1.service';
import { IBaseNewClass1 } from '@/types/NewClass1.types';

const useCreateNewClass1 = <T extends IBaseNewClass1>(
  onSuccess: (result: T) => void,
  onError: (e: Error | AxiosError) => void
) => {
  const queryClient = useQueryClient();

  type CreateRecordArgs = {
    newClass1: T;
    viewName: string;
  };

  const {
    mutate: createNewClass1,
    mutateAsync: createNewClass1Async,
    isPending,
  } = useMutation({
    mutationFn: (createRecordArgs: CreateRecordArgs) =>
      NewClass1Service.CreateNewClass1<T>(createRecordArgs.newClass1, createRecordArgs.viewName),
    onSuccess: (response, variables) => {
      const id = response.data.id;
      const { viewName } = variables;
      const className = 'newClass1';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list', viewName] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(response.data);
    },
    onError: (e) => onError(e),
  });

  return { createNewClass1, createNewClass1Async, isPending };
};

export default useCreateNewClass1;
