//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { NewClass1Service } from '@/services/NewClass1.service';

const useDeleteAllNewClass1 = (onSuccess: (result: string[]) => void, onError: (e: Error | AxiosError) => void) => {
  const queryClient = useQueryClient();

  const {
    mutate: deleteAllNewClass1,
    mutateAsync: deleteAllNewClass1Async,
    isPending,
  } = useMutation({
    mutationFn: (ids: string[]) => NewClass1Service.DeleteAllNewClass1(ids),
    onSuccess: (_, ids) => {
      const className = 'newClass1';
      ids.forEach((id) => {
        queryClient.removeQueries({ queryKey: [className, id] });
      });
      queryClient.invalidateQueries({ queryKey: [className, 'list'] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(ids);
    },
    onError: (e) => onError(e),
  });

  return { deleteAllNewClass1, deleteAllNewClass1Async, isPending };
};

export default useDeleteAllNewClass1;
