//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { NewClass1Service } from '@/services/NewClass1.service';

const useDeleteNewClass1 = (onSuccess: (result: string) => void, onError: (e: Error | AxiosError) => void) => {
  const queryClient = useQueryClient();

  const {
    mutate: deleteNewClass1,
    mutateAsync: deleteNewClass1Async,
    isPending,
  } = useMutation({
    mutationFn: (id: string) => NewClass1Service.DeleteNewClass1(id),
    onSuccess: (_, id) => {
      const className = 'newClass1';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list'] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(id);
    },
    onError: (e) => onError(e),
  });

  return { deleteNewClass1, deleteNewClass1Async, isPending };
};

export default useDeleteNewClass1;
