//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useEffect } from 'react';
import { isAxiosError } from 'axios';
import { useQuery } from '@tanstack/react-query';

import { NewClass1Service } from '@/services/NewClass1.service';
import type { IBaseNewClass1 } from '@/types/NewClass1.types';
import type { GetRequestOptions } from '@/types/helpers/GetRequestOptions';

const useGetNewClass1 = <T extends IBaseNewClass1>({ id, viewName, enabled = true, onNotFound }: GetRequestOptions) => {
  const { data, isLoading, isError, error } = useQuery({
    queryKey: ['newClass1', id],
    retry: false,
    enabled: enabled,
    queryFn: async (): Promise<T> => {
      const response = await NewClass1Service.GetNewClass1(id, viewName);
      return response.data;
    },
  });

  useEffect(() => {
    if (isError && isAxiosError(error)) {
      if (typeof onNotFound === 'function' && error.response?.status === 404) {
        onNotFound();
      }
    }
  }, [error, isError, onNotFound]);

  return {
    data,
    isLoading,
    isError,
  };
};

export default useGetNewClass1;
