//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { NewClass1Service } from '@/services/NewClass1.service';
import { IBaseNewClass1 } from '@/types/NewClass1.types';

const useUpdateNewClass1 = <T extends IBaseNewClass1>(
  onSuccess: (result: T) => void,
  onError: (e: Error | AxiosError) => void
) => {
  const queryClient = useQueryClient();

  type UpdateRecordArgs = {
    newClass1: T;
    viewName: string;
  };

  const {
    mutate: updateNewClass1,
    mutateAsync: updateNewClass1Async,
    isPending,
  } = useMutation({
    mutationFn: (updateRecordArgs: UpdateRecordArgs) =>
      NewClass1Service.UpdateNewClass1<T>(updateRecordArgs.newClass1, updateRecordArgs.viewName),
    onSuccess: (response, variables) => {
      const id = response.data.id;
      const { viewName } = variables;
      const className = 'newClass1';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list', viewName] });
      onSuccess(response.data);
    },
    onError: (e) => onError(e),
  });

  return { updateNewClass1, updateNewClass1Async, isPending };
};

export default useUpdateNewClass1;
